# Generated by Django 5.0.1 on 2026-01-27 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('job_cards', '0003_servicecategory_service'),
        ('pick_and_drop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickanddrop',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='pickanddrop',
            name='vehicle_details',
        ),
        migrations.AddField(
            model_name='pickanddrop',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_logs', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='pickanddrop',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_drop_logs', to='job_cards.jobcard'),
        ),
        migrations.AddField(
            model_name='pickanddrop',
            name='license_plate',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickanddrop',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickanddrop',
            name='vehicle_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pickanddrop',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pickanddrop',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('AT_WORKSHOP', 'At Workshop'), ('DROP_OFF_READY', 'Ready for Drop-off'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
