# Generated by Django 5.2.11 on 2026-02-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_and_drop', '0002_remove_pickanddrop_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickanddrop',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pickanddrop',
            name='current_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pickanddrop',
            name='last_updated_coords',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
