import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from finance.models import Account

def seed_coa():
    coa_data = [
        ('1010', 'Cash on Hand', 'Asset - Current'),
        ('1020', 'Bank Account – Operating', 'Asset - Current'),
        ('1021', 'Bank Account – POS Collections', 'Asset - Current'),
        ('1030', 'Accounts Receivable – Customers', 'Asset - Current'),
        ('1040', 'Advance to Employees', 'Asset - Current'),
        ('1050', 'Petty Cash', 'Asset - Current'),
        ('1060', 'Customer Deposit / Advance Received', 'Asset - Current'),
        ('1070', 'VAT Input Credit', 'Asset - Current'),
        ('1080', 'Inventory – Detailing Materials', 'Asset - Current'),
        ('1081', 'Inventory – Ceramic Coating', 'Asset - Current'),
        ('1082', 'Inventory – PPF Rolls', 'Asset - Current'),
        ('1083', 'Inventory – Paint & Chemical Material', 'Asset - Current'),
        ('1084', 'Inventory – Tools & Consumables', 'Asset - Current'),
        ('1090', 'Prepaid Expenses', 'Asset - Current'),
        ('1200', 'Machinery & Workshop Equipment', 'Asset - Fixed'),
        ('1210', 'Polishing Machines / Buffers', 'Asset - Fixed'),
        ('1220', 'PPF Plotter Machine', 'Asset - Fixed'),
        ('1230', 'Paint Booth', 'Asset - Fixed'),
        ('1240', 'AC Jacks / Lifts', 'Asset - Fixed'),
        ('1250', 'Furniture & Fixtures', 'Asset - Fixed'),
        ('1260', 'Computers & IT Equipment', 'Asset - Fixed'),
        ('1270', 'Motor Vehicles (Company Use)', 'Asset - Fixed'),
        ('1280', 'Leasehold Improvements', 'Asset - Fixed'),
        ('1290', 'Accumulated Depreciation', 'Asset - Fixed'),
        ('2010', 'Accounts Payable – Suppliers', 'Liability - Current'),
        ('2020', 'Staff Salary Payable', 'Liability - Current'),
        ('2030', 'End of Service Benefit (Accrued)', 'Liability - Current'),
        ('2040', 'Gratuity Provision', 'Liability - Current'),
        ('2050', 'VAT Payable', 'Liability - Current'),
        ('2060', 'Rent Payable', 'Liability - Current'),
        ('2070', 'Utilities Payable', 'Liability - Current'),
        ('2080', 'Customer Refund Payable', 'Liability - Current'),
        ('2090', 'Loan / Short Term Liability', 'Liability - Current'),
        ('2200', 'Bank Loan', 'Liability - Long Term'),
        ('2210', 'Equipment Finance Loan', 'Liability - Long Term'),
        ('2220', 'Vehicle Loan', 'Liability - Long Term'),
        ('3010', 'Owner Capital', 'Equity'),
        ('3020', 'Shareholder Drawings', 'Equity'),
        ('3030', 'Retained Earnings', 'Equity'),
        ('3040', 'Owner Contribution', 'Equity'),
        ('3050', 'Partner Loan Account', 'Equity'),
        ('4010', 'Car Detailing – Exterior', 'Revenue'),
        ('4011', 'Car Detailing – Interior', 'Revenue'),
        ('4012', 'Steam Wash / Deep Cleaning', 'Revenue'),
        ('4013', 'Engine Bay Cleaning', 'Revenue'),
        ('4014', 'Headlight Restoration', 'Revenue'),
        ('4015', 'Upholstery Shampoo / Seats Removal', 'Revenue'),
        ('4016', 'AC Cleaning / Ozone Treatment', 'Revenue'),
        ('4017', 'Polishing & Compounding', 'Revenue'),
        ('4018', 'Full Gold Package', 'Revenue'),
        ('4019', 'Silver Package', 'Revenue'),
        ('4100', 'PPF – Full Body', 'Revenue'),
        ('4101', 'PPF – Partial / Front', 'Revenue'),
        ('4102', 'PPF – Individual Panels', 'Revenue'),
        ('4103', 'PPF Material Sales', 'Revenue'),
        ('4200', 'Ceramic Coating Exterior', 'Revenue'),
        ('4201', 'Ceramic Coating Interior', 'Revenue'),
        ('4202', 'Ceramic Combo Package', 'Revenue'),
        ('4300', 'Window Tint – Premium', 'Revenue'),
        ('4301', 'Window Tint – Standard', 'Revenue'),
        ('4302', 'Sunroof Tinting', 'Revenue'),
        ('4400', 'Denting & Painting (Per Panel)', 'Revenue'),
        ('4401', 'Full Body Painting', 'Revenue'),
        ('4402', 'Alloy Wheel Painting', 'Revenue'),
        ('4403', 'Touch-Up Jobs', 'Revenue'),
        ('4404', 'Insurance Jobs', 'Revenue'),
        ('4405', 'Smart Repair & Spot Repair', 'Revenue'),
        ('4500', 'Pick & Drop Charges', 'Revenue'),
        ('4501', 'Accessories Sales', 'Revenue'),
        ('4502', 'Polishing Pads / Materials Sales', 'Revenue'),
        ('4503', 'Corporate Accounts', 'Revenue'),
        ('4504', 'Re-Inspection / Warranty Charges', 'Revenue'),
        ('4505', 'Membership Packages', 'Revenue'),
        ('5010', 'Detailing Chemicals Consumption', 'COGS'),
        ('5011', 'Ceramic Coating Bottles Usage', 'COGS'),
        ('5012', 'PPF Rolls Consumption', 'COGS'),
        ('5013', 'Paint & Thinner Consumption', 'COGS'),
        ('5014', 'Sandpaper / Consumables', 'COGS'),
        ('5015', 'Window Tint Film Consumption', 'COGS'),
        ('5016', 'Tools & Consumables Used', 'COGS'),
        ('5017', 'Freight & Import Charges', 'COGS'),
        ('5018', 'Inventory Adjustments', 'COGS'),
        ('6010', 'Staff Salaries', 'Expense'),
        ('6011', 'Technician Wages', 'Expense'),
        ('6012', 'Overtime Expense', 'Expense'),
        ('6013', 'Bonus / Incentives', 'Expense'),
        ('6014', 'Staff Accommodation', 'Expense'),
        ('6015', 'Staff Transportation', 'Expense'),
        ('6016', 'Visa / Medical / Insurance', 'Expense'),
        ('6017', 'Recruitment Costs', 'Expense'),
        ('6100', 'Rent', 'Expense'),
        ('6101', 'Water & Electricity', 'Expense'),
        ('6102', 'Internet & Phone', 'Expense'),
        ('6103', 'Workshop Maintenance', 'Expense'),
        ('6104', 'Machinery Repairs', 'Expense'),
        ('6105', 'Software / ERP / CRM', 'Expense'),
        ('6106', 'Office Supplies', 'Expense'),
        ('6107', 'Cleaning & Janitorial', 'Expense'),
        ('6108', 'Tool Maintenance', 'Expense'),
        ('6109', 'Car Wash Materials', 'Expense'),
        ('6110', 'Disposable Items', 'Expense'),
        ('6111', 'Fuel for Pick & Drop', 'Expense'),
        ('6112', 'Insurance', 'Expense'),
        ('6200', 'Social Media Ads – Meta', 'Expense'),
        ('6201', 'Google Ads', 'Expense'),
        ('6202', 'SEO & Website Hosting', 'Expense'),
        ('6203', 'Content Creation / Video', 'Expense'),
        ('6204', 'Influencer Marketing', 'Expense'),
        ('6205', 'Google Reviews Promotion', 'Expense'),
        ('6206', 'Printing & Branding', 'Expense'),
        ('6300', 'Office Rent', 'Expense'),
        ('6301', 'Legal & Consultancy', 'Expense'),
        ('6302', 'Bank Charges', 'Expense'),
        ('6303', 'Postage / Courier', 'Expense'),
        ('6304', 'IT Subscriptions', 'Expense'),
        ('6305', 'Depreciation Expense', 'Expense'),
        ('6306', 'Audit Fee', 'Expense'),
        ('6307', 'Government Fees', 'Expense'),
        ('6308', 'License Renewal', 'Expense'),
        ('7010', 'Discount Received', 'Other Income'),
        ('7020', 'Supplier Rebate', 'Other Income'),
        ('7030', 'Insurance Claim Income', 'Other Income'),
        ('7040', 'Scrap Material Income', 'Other Income'),
        ('8010', 'Penalties & Fines', 'Other Expense'),
        ('8020', 'Bad Debts', 'Other Expense'),
        ('8030', 'Inventory Loss', 'Other Expense'),
        ('8040', 'Bank Loan Interest', 'Other Expense'),
        ('8050', 'Settlement Write-Off', 'Other Expense'),
    ]

    for code, name, category in coa_data:
        Account.objects.update_or_create(
            code=code,
            defaults={'name': name, 'category': category}
        )
    print(f"Successfully seeded {len(coa_data)} accounts.")

if __name__ == '__main__':
    seed_coa()
