# Generated by Django 6.0.1 on 2026-01-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='assigned_bay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='assigned_technician',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='estimated_timeline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='feedback_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='floor_incharge_sign_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='initial_inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='post_work_head_sign_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='post_work_tl_sign_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='pre_work_head_sign_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='qc_sign_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='service_advisor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('RECEPTION', 'Step 1: Reception'), ('ESTIMATION', 'Step 2: Estimation'), ('WORK_ASSIGNMENT', 'Step 3: Work Assignment'), ('WIP', 'Step 4: Work In Progress'), ('QC', 'Step 5: QC Approval'), ('INVOICING', 'Step 6: Invoicing'), ('DELIVERY', 'Step 7: Delivery'), ('CLOSED', 'Job Card Closed')], default='RECEPTION', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='JobCardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_card_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='job_cards.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('parts_consumed', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='job_cards.jobcard')),
            ],
        ),
    ]
