# Generated by Django 5.0.1 on 2026-01-27 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0005_jobcard_signature_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='portal_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
