# Generated by Django 5.0.1 on 2026-01-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_signature_data'),
        ('job_cards', '0006_jobcard_portal_token'),
        ('leads', '0005_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='related_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='related_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='leads.lead'),
        ),
    ]
