# Generated by Django 5.0.1 on 2026-01-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0007_jobcard_related_booking_jobcard_related_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='plate_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='plate_emirate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
