# Generated by Django 5.0.1 on 2026-01-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0008_jobcard_plate_code_jobcard_plate_emirate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('RECEPTION', 'Reception'), ('ESTIMATION', 'Estimation'), ('WORK_ASSIGNMENT', 'Work Assignment'), ('WIP', 'Work In Progress'), ('QC', 'Quality Check'), ('INVOICING', 'Invoicing'), ('DELIVERY', 'Ready for Delivery'), ('CLOSED', 'Closed')], default='RECEPTION', max_length=20),
        ),
    ]
