# Generated by Django 5.2.11 on 2026-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0009_alter_jobcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
