# Generated by Django 5.2.11 on 2026-02-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_employee_commission_rate_and_more'),
        ('job_cards', '0010_alter_jobcard_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='advisor_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='assigned_technician_legacy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='commission_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='service_advisor_legacy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='technician_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='service_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_jobs', to='hr.employee'),
        ),
    ]
