# Generated by Django 5.2.11 on 2026-02-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0012_alter_jobcard_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('RECEPTION', 'Reception'), ('ESTIMATION_ASSIGNMENT', 'Estimation & Assignment'), ('WIP_QC', 'Work In Progress & QC'), ('INVOICING_DELIVERY', 'Invoicing & Delivery'), ('CLOSED', 'Closed')], default='RECEPTION', max_length=25),
        ),
    ]
