# Generated by Django 5.2.11 on 2026-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0013_alter_jobcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='sla_clock_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
