# Generated by Django 5.2.11 on 2026-02-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0014_jobcard_sla_clock_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='is_released',
            field=models.BooleanField(default=False, help_text='Released by manager for scheduling/workshop'),
        ),
    ]
