# Generated by Django 5.2.11 on 2026-02-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0015_jobcard_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], default='Mr', max_length=10),
        ),
        migrations.AddField(
            model_name='jobcardphoto',
            name='panel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
