# Generated by Django 5.2.11 on 2026-02-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0016_jobcard_title_jobcardphoto_panel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='plate_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
