# Generated by Django 5.2.11 on 2026-02-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_stripe_customer_id'),
        ('job_cards', '0017_jobcard_plate_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received (Reception)'), ('IN_PROGRESS', 'In Process (Workshop)'), ('READY', 'Ready for Quality Control'), ('INVOICED', 'Invoiced (Accounted)'), ('CLOSED', 'Closed & Delivered')], default='RECEPTION', max_length=25),
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('PPF', 'Paint Protection Film'), ('WRAP', 'Vinyl Wrap'), ('TINT', 'Window Tinting'), ('PAINT', 'Body Paint'), ('CERAMIC', 'Ceramic Coating')], max_length=20)),
                ('issue_description', models.TextField()),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Inspection'), ('APPROVED', 'Approved for Re-work'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Claim Resolved')], default='PENDING', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='customers.customer')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='job_cards.jobcard')),
            ],
        ),
    ]
