# Generated by Django 5.2.11 on 2026-02-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0018_alter_jobcard_status_warrantyclaim'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='masters.vehicle'),
        ),
    ]
