# Generated by Django 5.2.11 on 2026-02-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0019_jobcard_vehicle_node'),
        ('workshop', '0002_booth_paintmix'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='current_booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='workshop.booth'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='paint_stage',
            field=models.CharField(choices=[('NONE', 'Not Required'), ('PENDING_MIX', 'Pending Paint Mixing'), ('STRIPPING', 'Stripping/Prep'), ('PRIMER', 'Primer Application'), ('BASE_COAT', 'Base Coat'), ('CLEAR_COAT', 'Clear Coat'), ('BAKING', 'Baking'), ('QC', 'Paint Quality Control'), ('COMPLETED', 'Paint Work Completed')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received (Reception)'), ('IN_PROGRESS', 'In Process (Workshop)'), ('READY', 'Ready for Quality Control'), ('INVOICED', 'Invoiced (Accounted)'), ('CLOSED', 'Closed & Delivered')], default='RECEIVED', max_length=25),
        ),
    ]
