# Generated by Django 5.2.11 on 2026-02-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0020_jobcard_current_booth_jobcard_paint_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='kilometers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
