# Generated by Django 5.2.11 on 2026-02-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_audit_id_transaction_regulatory_status_and_more'),
        ('hr', '0019_department_expense_account_department_income_account'),
        ('job_cards', '0021_alter_jobcard_brand_alter_jobcard_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='jobcard',
            name='appointment_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='attendee',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='brought_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='checklist_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_approval_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='WAITING', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_estimated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='cylinder_type',
            field=models.CharField(blank=True, help_text='e.g. 4, 6, 8, 12 Cylinder', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='estimation_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='inspection_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_category',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Campaign', 'Campaign'), ('Warranty', 'Warranty'), ('Internal', 'Internal')], default='Regular', max_length=50),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='mulkiya_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='no_of_days',
            field=models.IntegerField(default=0, help_text='Estimated days for completion'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_jobs', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='service',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated cost to company', max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='hr.department'),
        ),
        migrations.AddField(
            model_name='service',
            name='income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='finance.account'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_icons/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='JobCardRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_list', to='job_cards.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='job_cards.jobcard')),
            ],
        ),
    ]
