# Generated by Django 5.2.11 on 2026-02-20 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_bonus_employeebankdetails_employeededuction_and_more'),
        ('job_cards', '0022_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='committed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_jobs', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('VVIP', 'VVIP')], max_length=50),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='revise_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_jobs', to='hr.employee', verbose_name='Sales Man'),
        ),
    ]
