# Generated by Django 5.2.11 on 2026-02-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0023_jobcard_committed_date_jobcard_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='actual_days',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Actual days taken', max_digits=5),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='efficiency_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated efficiency score', max_digits=5),
        ),
    ]
