# Generated by Django 5.0.1 on 2026-01-28 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0008_branch_company_employee_branch_branch_company_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('probability', models.IntegerField(choices=[(1, 'Rare'), (2, 'Possible'), (3, 'Likely'), (4, 'Certain')], default=2)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MITIGATING', 'Mitigating'), ('MITIGATED', 'Mitigated'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('escalation_level', models.CharField(choices=[('NONE', 'None'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('EXECUTIVE', 'Executive')], default='NONE', max_length=20)),
                ('residual_risk', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='hr.department')),
                ('linked_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='projects.project')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact_description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('resolution', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='hr.employee')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='risk_management.risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskMitigationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('effectiveness_rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_tasks', to='hr.employee')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_actions', to='risk_management.risk')),
            ],
        ),
    ]
