# Generated by Django 6.0.1 on 2026-01-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('job_cards', '0002_jobcard_assigned_bay_jobcard_assigned_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='job_cards.jobcard'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
