# Generated by Django 6.0.1 on 2026-01-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_job_card_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='department',
            field=models.CharField(default='OPERATIONS', max_length=50),
        ),
    ]
