# Generated by Django 5.0.1 on 2026-01-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_department'),
        ('invoices', '0003_invoice_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='finance_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_invoice', to='finance.transaction'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='department',
            field=models.CharField(choices=[('MARKETING', 'Marketing'), ('OPERATIONS', 'Operations'), ('HR', 'HR & Visa'), ('INVENTORY', 'Inventory'), ('GENERAL', 'General & Admin')], default='OPERATIONS', max_length=50),
        ),
    ]
