# Generated by Django 5.0.1 on 2026-01-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_finance_transaction_alter_invoice_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
