# Generated by Django 5.0.1 on 2026-01-28 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_department_team_department'),
        ('invoices', '0005_invoice_signature_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='hr.department'),
        ),
    ]
