# Generated by Django 5.0.1 on 2026-01-28 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_department_ref'),
        ('job_cards', '0006_jobcard_portal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='job_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='job_cards.jobcard'),
        ),
    ]
