# Generated by Django 5.0.1 on 2026-01-29 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_job_card'),
        ('job_cards', '0006_jobcard_portal_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total advance payments received', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance after advances', max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_slip_number', models.CharField(max_length=50, unique=True)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('ADVANCE', 'Advance Payment'), ('PARTIAL', 'Partial Payment'), ('FINAL', 'Final Payment'), ('REFUND', 'Refund')], default='ADVANCE', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment')], default='CASH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('received_by', models.CharField(blank=True, help_text='Employee who received the payment', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='invoices.invoice')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='job_cards.jobcard')),
            ],
        ),
    ]
