# Generated by Django 5.0.1 on 2026-01-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_advance_paid_invoice_balance_due_payment'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='locations.branch'),
        ),
    ]
