# Generated by Django 5.2.11 on 2026-02-20 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_transaction_account'),
        ('invoices', '0010_invoice_vehicle_brand_invoice_vehicle_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='finance_transaction',
        ),
        migrations.AddField(
            model_name='invoice',
            name='finance_voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_invoice', to='finance.voucher'),
        ),
    ]
