# Generated by Django 5.2.11 on 2026-02-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100, unique=True, verbose_name='VIN/Chassis')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Plate Number')),
                ('plate_emirate', models.CharField(default='Dubai', max_length=50)),
                ('plate_code', models.CharField(blank=True, max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('chassis_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Vehicle Node',
                'verbose_name_plural': 'Vehicle Registry',
            },
        ),
    ]
