# Generated by Django 5.2.11 on 2026-02-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_vehiclebrand_vehicle_brand_node_vehiclemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('trn', models.CharField(blank=True, max_length=50, verbose_name='TRN / Tax ID')),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. 30 Days Credit', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Insurance Companies',
            },
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(default='#000000', help_text='Hex color code (e.g. #FF0000)', max_length=7)),
            ],
        ),
    ]
