# Generated by Django 5.0.1 on 2026-01-30 12:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_loyalty_points_customer_preferred_services_and_more'),
        ('invoices', '0008_invoice_advance_paid_invoice_balance_due_payment'),
        ('job_cards', '0008_jobcard_plate_code_jobcard_plate_emirate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLevelAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('CORPORATE', 'Corporate Fleet'), ('DEALERSHIP', 'Dealership'), ('RENTAL', 'Rental Company'), ('INSURANCE', 'Insurance Partner'), ('GOVERNMENT', 'Government'), ('INDIVIDUAL', 'Individual Commercial')], max_length=50)),
                ('agreement_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('service_level', models.CharField(choices=[('PLATINUM', 'Platinum (24/7)'), ('GOLD', 'Gold (Business Hours)'), ('SILVER', 'Silver (Next Business Day)'), ('BRONZE', 'Bronze (48 Hours)')], max_length=50)),
                ('emergency_response_time', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('standard_response_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)])),
                ('resolution_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('service_credit_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_service_credit', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('monthly_retainer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority_surcharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('auto_renew', models.BooleanField(default=True)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('termination_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('signed_by', models.CharField(blank=True, max_length=100)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SLAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('on_time_responses', models.IntegerField(default=0)),
                ('average_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_jobs', models.IntegerField(default=0)),
                ('on_time_completions', models.IntegerField(default=0)),
                ('average_completion_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_satisfaction_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rework_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('service_credits_issued', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_impact', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.servicelevelagreement')),
            ],
        ),
        migrations.CreateModel(
            name='SLARenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_months', models.IntegerField()),
                ('new_end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.servicelevelagreement')),
                ('renewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SLAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('MONTHLY', 'Monthly Performance Report'), ('QUARTERLY', 'Quarterly Business Review'), ('ANNUAL', 'Annual Contract Review'), ('ADHOC', 'Ad-hoc Report')], max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('overall_compliance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_violations', models.IntegerField(default=0)),
                ('total_service_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('executive_summary', models.TextField()),
                ('detailed_analysis', models.TextField()),
                ('recommendations', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_customer', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer_acknowledged', models.BooleanField(default=False)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='sla_reports/%Y/%m/')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.servicelevelagreement')),
            ],
        ),
        migrations.CreateModel(
            name='SLAViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('RESPONSE_TIME', 'Response Time Exceeded'), ('RESOLUTION_TIME', 'Resolution Time Exceeded'), ('QUALITY', 'Quality Issue'), ('AVAILABILITY', 'Service Unavailable'), ('COMMUNICATION', 'Communication Failure')], max_length=50)),
                ('violation_date', models.DateTimeField()),
                ('expected_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_exceeded', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('service_credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_adjusted', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_violations', to=settings.AUTH_USER_MODEL)),
                ('adjusted_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_cards.jobcard')),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.servicelevelagreement')),
            ],
        ),
        migrations.AddIndex(
            model_name='servicelevelagreement',
            index=models.Index(fields=['agreement_number'], name='contracts_s_agreeme_d36f57_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelevelagreement',
            index=models.Index(fields=['customer', 'is_active'], name='contracts_s_custome_bbc320_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelevelagreement',
            index=models.Index(fields=['end_date'], name='contracts_s_end_dat_647c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='slametric',
            index=models.Index(fields=['sla', 'month'], name='contracts_s_sla_id_312c07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slametric',
            unique_together={('sla', 'month')},
        ),
        migrations.AddIndex(
            model_name='slareport',
            index=models.Index(fields=['sla', 'period_end'], name='contracts_s_sla_id_546b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='slaviolation',
            index=models.Index(fields=['sla', 'violation_date'], name='contracts_s_sla_id_fddcff_idx'),
        ),
        migrations.AddIndex(
            model_name='slaviolation',
            index=models.Index(fields=['violation_type'], name='contracts_s_violati_49332f_idx'),
        ),
    ]
