# Generated by Django 6.0.1 on 2026-01-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('technician_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('vin', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
