# Generated by Django 5.2.11 on 2026-02-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('job_cards', '0010_alter_jobcard_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='job_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='job_cards.jobcard'),
        ),
    ]
