# Generated by Django 5.0.1 on 2026-01-29 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_employeedocument_salaryslip_warningletter'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_type', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_number', models.CharField(max_length=50, unique=True)),
                ('pickup_date', models.DateTimeField(db_index=True)),
                ('pickup_location', models.TextField()),
                ('vehicle_registration', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pickup'), ('COLLECTED', 'Collected'), ('IN_TRANSIT', 'In Transit to Warehouse'), ('RECEIVED', 'Received at Warehouse'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('items_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='logistics.customer')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='hr.employee')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='logistics.shipment')),
            ],
        ),
    ]
