# Generated by Django 5.0.1 on 2026-01-29 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('hr', '0010_employeedocument_salaryslip_warningletter'),
        ('job_cards', '0006_jobcard_portal_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_number', models.CharField(max_length=50, unique=True)),
                ('delay_reason', models.CharField(max_length=255)),
                ('detailed_reason', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Minor Delay (1-2 hours)'), ('MEDIUM', 'Moderate Delay (3-6 hours)'), ('HIGH', 'Significant Delay (6+ hours)'), ('CRITICAL', 'Major Delay (24+ hours)')], default='LOW', max_length=20)),
                ('original_completion_date', models.DateTimeField()),
                ('new_estimated_completion_date', models.DateTimeField()),
                ('delay_duration_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('corrective_action_taken', models.TextField(blank=True)),
                ('customer_informed', models.BooleanField(default=False)),
                ('customer_informed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_response', models.TextField(blank=True)),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_borne_by', models.CharField(choices=[('COMPANY', 'Company'), ('CUSTOMER', 'Customer'), ('STAFF', 'Staff Responsibility')], default='COMPANY', max_length=100)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('CUSTOMER_INFORMED', 'Customer Informed'), ('APPROVED', 'Extention Approved'), ('RESOLVED', 'Delay Resolved')], default='REPORTED', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_delays', to='hr.employee')),
                ('customer_informed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informed_delays', to='hr.employee')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='job_cards.jobcard')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_delays', to='hr.employee')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_cards.service')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(max_length=50, unique=True)),
                ('incident_type', models.CharField(choices=[('VEHICLE_DAMAGE', 'Vehicle Damage during Service'), ('EQUIPMENT_FAILURE', 'Equipment Failure'), ('STAFF_INJURY', 'Staff Injury'), ('CUSTOMER_DISPUTE', 'Customer Dispute'), ('LOST_ITEM', 'Lost Property')], max_length=50)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor (No cost/Low risk)'), ('MAJOR', 'Major (Cost/Risk involved)'), ('SEVERE', 'Severe (Legal/Safety concern)')], default='MINOR', max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('incident_location', models.CharField(max_length=255)),
                ('incident_description', models.TextField()),
                ('what_happened', models.TextField(help_text='Detailed sequence of events')),
                ('how_it_happened', models.TextField(help_text='Root cause analysis')),
                ('witnesses', models.TextField(blank=True)),
                ('customer_notified', models.BooleanField(default=False)),
                ('customer_notified_at', models.DateTimeField(blank=True, null=True)),
                ('damage_description', models.TextField(blank=True)),
                ('damage_photos', models.JSONField(blank=True, default=list)),
                ('estimated_repair_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actual_repair_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('insurance_claim_filed', models.BooleanField(default=False)),
                ('insurance_claim_number', models.CharField(blank=True, max_length=100)),
                ('insurance_company', models.CharField(blank=True, max_length=255)),
                ('claim_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_affected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='job_cards.jobcard')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_incidents', to='hr.employee')),
            ],
        ),
    ]
