# Generated by Django 5.2.11 on 2026-02-18 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_employee_full_name_passport_and_more'),
        ('job_cards', '0019_jobcard_vehicle_node'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('READY', 'Ready / Empty'), ('ACTIVE', 'Active / Painting'), ('BAKING', 'Baking Cycle'), ('MAINTENANCE', 'Maintenance'), ('QC', 'Quality Control')], default='READY', max_length=20)),
                ('temperature', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, default=45.0, max_digits=5)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_booth', to='job_cards.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='PaintMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_code', models.CharField(max_length=100)),
                ('color_name', models.CharField(max_length=255)),
                ('formula_data', models.JSONField(default=dict, help_text='Detailed mix weights')),
                ('total_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in Liters', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_mixes', to='job_cards.jobcard')),
                ('mixed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_mixes', to='hr.employee')),
            ],
        ),
    ]
