# Generated by Django 6.0.1 on 2026-01-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.CharField(choices=[('MARKETING', 'Marketing'), ('OPERATIONS', 'Operations'), ('HR', 'HR & Visa'), ('INVENTORY', 'Inventory'), ('GENERAL', 'General & Admin')], default='GENERAL', max_length=50),
        ),
    ]
