# Generated by Django 5.0.1 on 2026-01-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budget_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='department',
            field=models.CharField(choices=[('MARKETING', 'Marketing'), ('OPERATIONS', 'Operations'), ('HR', 'HR & Visa'), ('INVENTORY', 'Inventory'), ('GENERAL', 'General & Admin')], default='GENERAL', max_length=50),
        ),
    ]
