# Generated by Django 5.0.1 on 2026-01-28 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_department'),
        ('hr', '0004_department_team_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='hr.department'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='hr.department'),
        ),
    ]
