# Generated by Django 5.2.11 on 2026-02-10 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_receipt_to_transaction'),
        ('hr', '0016_employee_commission_rate_and_more'),
        ('job_cards', '0010_alter_jobcard_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='audit_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='regulatory_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized'), ('VOID', 'Voided')], default='FINAL', max_length=50),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACCRUED', 'Accrued (Unpaid)'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='ACCRUED', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='hr.employee')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='job_cards.jobcard')),
            ],
        ),
    ]
