# Generated by Django 5.2.11 on 2026-02-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
    ]
