# Generated by Django 5.2.11 on 2026-02-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_transaction_account'),
        ('invoices', '0011_remove_invoice_finance_transaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
