# Generated by Django 5.2.11 on 2026-02-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_delete_transaction'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('EQUIPMENT', 'Workshop Equipment'), ('VEHICLE', 'Company Vehicle'), ('FURNITURE', 'Office Furniture'), ('ELECTRONICS', 'IT & Electronics'), ('LAND', 'Land & Property')], max_length=20)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('useful_life_years', models.PositiveIntegerField(help_text='Expected life in years')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.branch')),
            ],
        ),
        migrations.CreateModel(
            name='LinkingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('PAYROLL', 'Payroll'), ('INVENTORY', 'Inventory'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('CASH_IN_HAND', 'Cash in Hand'), ('BANK', 'Bank Accounts')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_modules', to='finance.account')),
            ],
        ),
    ]
