# Generated by Django 6.0.1 on 2026-01-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPFWarrantyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50, verbose_name='VIN')),
                ('installation_date', models.DateField()),
                ('branch_location', models.CharField(choices=[('DXB', 'Dubai'), ('AUH', 'Abu Dhabi'), ('SHJ', 'Sharjah')], max_length=10)),
                ('film_brand', models.CharField(max_length=100)),
                ('film_type', models.CharField(choices=[('GLOSS', 'Gloss'), ('MATTE', 'Matte'), ('CERAMIC', 'Ceramic')], max_length=20)),
                ('coverage_area', models.CharField(max_length=255)),
                ('first_checkup_date', models.DateField(blank=True, null=True)),
                ('first_checkup_notes', models.TextField(blank=True, null=True)),
                ('second_checkup_date', models.DateField(blank=True, null=True)),
                ('second_checkup_notes', models.TextField(blank=True, null=True)),
                ('third_checkup_date', models.DateField(blank=True, null=True)),
                ('third_checkup_notes', models.TextField(blank=True, null=True)),
                ('fourth_checkup_date', models.DateField(blank=True, null=True)),
                ('fourth_checkup_notes', models.TextField(blank=True, null=True)),
                ('fifth_checkup_date', models.DateField(blank=True, null=True)),
                ('fifth_checkup_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
