# Generated by Django 6.0.1 on 2026-01-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_job_card_alter_invoice_payment_status'),
        ('ppf_warranty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppfwarrantyregistration',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppf_warranty', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='ppfwarrantyregistration',
            name='film_type',
            field=models.CharField(choices=[('GLOSS', 'Gloss'), ('MATTE', 'Matte'), ('SATIN', 'Satin'), ('VINYL', 'Vinyl Wrap'), ('COLOR', 'Color PPF'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ppfwarrantyregistration',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
