# Generated by Django 5.0.1 on 2026-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppf_warranty', '0002_ppfwarrantyregistration_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppfwarrantyregistration',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
