# Generated by Django 6.0.1 on 2026-02-08 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppf_warranty', '0003_ppfwarrantyregistration_signature_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppfwarrantyregistration',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppfwarrantyregistration',
            name='film_lot_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ppfwarrantyregistration',
            name='portal_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='ppfwarrantyregistration',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='warranty_qr_codes/'),
        ),
        migrations.AddField(
            model_name='ppfwarrantyregistration',
            name='roll_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ppfwarrantyregistration',
            name='warranty_duration_years',
            field=models.IntegerField(choices=[(2, '2 Years'), (5, '5 Years'), (10, '10 Years - Lifetime')], default=5),
        ),
    ]
