# Generated by Django 5.0.1 on 2026-01-27 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('hr', '0001_initial'),
        ('job_cards', '0003_servicecategory_service'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_bookings', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='related_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_cards.servicecategory'),
        ),
        migrations.AddField(
            model_name='booking',
            name='v_registration_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Vehicle Arrived'), ('CANCELLED', 'Cancelled'), ('NOSHOW', 'No Show')], default='PENDING', max_length=50),
        ),
    ]
