# Generated by Django 5.0.1 on 2026-01-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
