# Generated by Django 5.2.11 on 2026-02-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_signature_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='v_registration_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
