# Generated by Django 5.2.11 on 2026-02-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_v_registration_no_and_more'),
        ('job_cards', '0013_alter_jobcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_cards.service'),
        ),
    ]
