# Generated by Django 5.2.11 on 2026-02-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
