# Generated by Django 5.0.1 on 2026-01-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('leads', '0002_remove_lead_budget_lead_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers.customer'),
        ),
    ]
