# Generated by Django 5.0.1 on 2026-01-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('WHATSAPP', 'WhatsApp'), ('GMAIL', 'Gmail'), ('COBONE', 'Cobone'), ('GROUPON', 'Groupon'), ('TABBY', 'Tabby'), ('WALKIN', 'Walk-in'), ('REFERENCE', 'Reference / Referral'), ('WEBSITE', 'Website'), ('EXISTING', 'Existing Customer')], max_length=50),
        ),
    ]
