# Generated by Django 5.0.1 on 2026-01-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('INBOX', 'Inbox / Ghost'), ('NEW', 'New Lead'), ('CONTACTED', 'First Contact'), ('NEGOTIATION', 'Negotiation'), ('QUOTED', 'Quote Sent'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=50),
        ),
    ]
