# Generated by Django 5.2.11 on 2026-02-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_leadphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='interested_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
