# Generated by Django 5.2.11 on 2026-02-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_branch'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='vehicle_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='masters.vehicle'),
        ),
    ]
