# Generated by Django 6.0.1 on 2026-01-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accent_color',
            field=models.CharField(default='#b08d57', max_length=7),
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
