# Generated by Django 5.0.1 on 2026-01-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='monthly_expense_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='monthly_sales_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
