# Generated by Django 5.0.1 on 2026-01-28 10:11

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_department_monthly_expense_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_1_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_1_photo',
            field=models.ImageField(blank=True, null=True, upload_to='emergency_contacts/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_1_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_2_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_2_photo',
            field=models.ImageField(blank=True, null=True, upload_to='emergency_contacts/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_2_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_summary',
            field=models.TextField(blank=True, help_text='Summary of past experience and skills.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='family_members_count',
            field=models.IntegerField(default=0, help_text='Number of immediate family members in home country.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Past medical history and conditions.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.db.models.functions.datetime.Now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be deducted.', max_digits=10)),
                ('description', models.TextField(help_text='Description of the mistake or breakage.')),
                ('evidence_photo', models.ImageField(help_text='Photo evidence of the mistake.', upload_to='mistakes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='hr.employee')),
            ],
        ),
    ]
