# Generated by Django 5.0.1 on 2026-01-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_branch_company_employee_branch_branch_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('PARENT', 'Parent Company'), ('SUBSIDIARY', 'Subsidiary'), ('DIVISION', 'Division/Department')], default='PARENT', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='hr.company'),
        ),
    ]
