# Generated by Django 5.0.1 on 2026-01-29 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_company_company_type_company_parent_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('VISA', 'Visa'), ('ID', 'Emirates ID'), ('CONTRACT', 'Labor Contract'), ('LICENSE', 'Driving License'), ('OTHER', 'Other')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('file', models.FileField(upload_to='employee_docs/')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('warning_level', models.CharField(choices=[('VERBAL', 'Verbal Warning'), ('FIRST', 'First Written Warning'), ('SECOND', 'Second Written Warning'), ('FINAL', 'Final Warning')], max_length=20)),
                ('reason', models.TextField()),
                ('consequences', models.TextField(blank=True)),
                ('is_signed_by_employee', models.BooleanField(default=False)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='hr.employee')),
            ],
        ),
    ]
