# Generated by Django 5.0.1 on 2026-01-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_employeedocument_salaryslip_warningletter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hrattendance',
            unique_together={('employee', 'date')},
        ),
    ]
