# Generated by Django 5.0.1 on 2026-01-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_hrattendance_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryslip',
            old_name='created_at',
            new_name='generated_at',
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='days_present',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='late_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_additions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='month',
            field=models.CharField(help_text='Format: YYYY-MM', max_length=7),
        ),
    ]
