# Generated by Django 5.0.1 on 2026-01-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_rename_created_at_salaryslip_generated_at_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='locations.branch'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
