# Generated by Django 6.0.1 on 2026-02-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_alter_employee_branch_delete_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_1_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_1_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_1_photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_1_relation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_2_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_2_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_2_photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_2_relation',
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_emer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_emer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_emer_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='home_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('DAILY', 'Daily (Attendance Based)'), ('HOURLY', 'Hourly')], default='MONTHLY', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uae_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uae_emer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uae_emer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uae_emer_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uae_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='visa_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
