# Generated by Django 5.2.11 on 2026-02-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default commission percentage (e.g. 5.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_commissions_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='commissions_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
