# Generated by Django 5.2.11 on 2026-02-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_employee_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_financials', 'Can view employee financial details')]},
        ),
    ]
