# Generated by Django 5.2.11 on 2026-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name_passport',
            field=models.CharField(blank=True, help_text='Official name as per passport.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='permissions_config',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic JSON for granular portfolio and system access.'),
        ),
    ]
