# Generated by Django 5.2.11 on 2026-02-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_audit_id_transaction_regulatory_status_and_more'),
        ('hr', '0018_employee_full_name_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='Default Expense Account for this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_departments', to='finance.account'),
        ),
        migrations.AddField(
            model_name='department',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Default Income/Revenue Account for this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_departments', to='finance.account'),
        ),
    ]
