# Generated by Django 5.2.11 on 2026-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
