# Generated by Django 5.0.1 on 2026-01-29 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0009_company_company_type_company_parent_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_invoices', models.IntegerField(default=0)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('detailing_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ppf_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ceramic_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_customers', models.IntegerField(default=0)),
                ('repeat_customers', models.IntegerField(default=0)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['report_date'], name='reports_dai_report__d27c9a_idx'), models.Index(fields=['-report_date'], name='reports_dai_report__82b79a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=7, unique=True)),
                ('year', models.IntegerField()),
                ('month_number', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_invoices', models.IntegerField(default=0)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('detailing_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ppf_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ceramic_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_customers_total', models.IntegerField(default=0)),
                ('repeat_customers_total', models.IntegerField(default=0)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('marketing_leads', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month_number'],
                'indexes': [models.Index(fields=['year', 'month_number'], name='reports_mon_year_99d31e_idx'), models.Index(fields=['-year', '-month_number'], name='reports_mon_year_bb648d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('COMPANY', 'Company-wide'), ('DEPARTMENT', 'Department'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('month', models.CharField(max_length=7)),
                ('revenue_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jobs_target', models.IntegerField(default=0)),
                ('new_customers_target', models.IntegerField(default=0)),
                ('revenue_achieved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jobs_achieved', models.IntegerField(default=0)),
                ('new_customers_achieved', models.IntegerField(default=0)),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('target_type', 'month', 'department', 'employee')},
            },
        ),
    ]
