# Generated by Django 5.0.1 on 2026-01-29 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chatmessage'),
        ('hr', '0009_company_company_type_company_parent_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('report_type', models.CharField(choices=[('DEPARTMENT_HEAD', 'Department Head Report'), ('OPERATIONS_MANAGER', 'Operations Manager Report'), ('MANAGER', 'Manager Report'), ('SERVICE_ADVISOR', 'Service Advisor Report'), ('MEDIA_TEAM', 'Media Team Report')], max_length=30)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('FULL_DAY', 'Full Day')], default='FULL_DAY', max_length=20)),
                ('summary', models.TextField(help_text="Brief summary of the day's activities")),
                ('jobs_completed', models.IntegerField(default=0, help_text='Number of jobs completed today')),
                ('jobs_in_progress', models.IntegerField(default=0, help_text='Number of jobs currently in progress')),
                ('new_customers', models.IntegerField(default=0, help_text='New customers acquired')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Revenue generated today', max_digits=10)),
                ('photos_uploaded', models.IntegerField(default=0, help_text='Number of photos uploaded (Media Team)')),
                ('videos_uploaded', models.IntegerField(default=0, help_text='Number of videos uploaded (Media Team)')),
                ('issues_faced', models.TextField(blank=True, help_text='Any issues or challenges faced today')),
                ('pending_tasks', models.TextField(blank=True, help_text='Tasks pending for next day')),
                ('team_attendance', models.CharField(blank=True, help_text="e.g., '8/10 present'", max_length=255)),
                ('team_notes', models.TextField(blank=True, help_text='Notes about team performance')),
                ('closing_notes', models.TextField(blank=True, help_text='End of day closing notes')),
                ('next_day_plan', models.TextField(blank=True, help_text='Plan for next day')),
                ('reviewed_by_radhir', models.BooleanField(default=False)),
                ('reviewed_by_ruchika', models.BooleanField(default=False)),
                ('reviewed_by_afsar', models.BooleanField(default=False)),
                ('radhir_comments', models.TextField(blank=True)),
                ('ruchika_comments', models.TextField(blank=True)),
                ('afsar_comments', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='hr.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='hr.employee')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'unique_together': {('employee', 'report_date', 'shift')},
            },
        ),
    ]
