# Generated by Django 5.2.11 on 2026-02-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dailyreport'),
        ('pick_and_drop', '0003_pickanddrop_current_lat_pickanddrop_current_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='pick_and_drop.pickanddrop'),
        ),
    ]
