# Generated by Django 5.0.1 on 2026-01-28 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0003_employee_accent_color_employee_bio_and_more'),
        ('leads', '0003_lead_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('target_url', models.URLField()),
                ('current_ranking', models.IntegerField(default=0)),
                ('previous_ranking', models.IntegerField(default=0)),
                ('monthly_volume', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_keywords', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('YOUTUBE', 'YouTube'), ('LINKEDIN', 'LinkedIn')], max_length=20)),
                ('content_type', models.CharField(choices=[('REEL', 'Reel / Short'), ('POST', 'Static Post'), ('STORY', 'Story'), ('AD', 'Paid Advertisement')], max_length=20)),
                ('post_date', models.DateTimeField()),
                ('link', models.URLField(blank=True)),
                ('engagement_likes', models.IntegerField(default=0)),
                ('engagement_comments', models.IntegerField(default=0)),
                ('engagement_shares', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='hr.employee')),
                ('leads_generated', models.ManyToManyField(blank=True, related_name='sourced_posts', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('SHOOTING', 'Shooting'), ('EDITING', 'In Editing'), ('REVIEW', 'Client Review'), ('PUBLISHED', 'Published')], default='PLANNING', max_length=20)),
                ('raw_footage_link', models.URLField(blank=True)),
                ('final_video_link', models.URLField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('videographer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_projects', to='hr.employee')),
            ],
        ),
    ]
