# Generated by Django 5.0.1 on 2026-01-27 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_booking_customer_profile'),
        ('job_cards', '0004_jobcard_customer_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('targets', models.TextField(blank=True)),
                ('receiving_count', models.PositiveIntegerField(default=0)),
                ('delivery_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('DETAILING', 'Detailing'), ('PAINTING', 'Painting'), ('PPF_WRAPPING', 'PPF & Wrapping')], max_length=20)),
                ('leader', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('spacer', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_jobs_received', models.PositiveIntegerField(default=0)),
                ('total_jobs_delivered', models.PositiveIntegerField(default=0)),
                ('revenue_daily', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('summary_notes', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_number', models.PositiveIntegerField()),
                ('is_overtime', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_cards.jobcard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.workteam')),
            ],
            options={
                'unique_together': {('team', 'date', 'slot_number', 'is_overtime')},
            },
        ),
    ]
