# Generated by Django 5.0.1 on 2026-01-27 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('role', models.CharField(choices=[('SALES', 'Sales/Service Advisor'), ('ACCOUNTS', 'Accounts/Finance'), ('OPERATIONS', 'Workshop Operations'), ('GENERAL', 'General Staff')], max_length=20)),
                ('tasks_completed', models.TextField(blank=True, help_text='List of tasks done today')),
                ('upsell_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('upsell_count', models.PositiveIntegerField(default=0)),
                ('complaints_received', models.PositiveIntegerField(default=0)),
                ('complaints_resolved', models.PositiveIntegerField(default=0)),
                ('new_bookings', models.PositiveIntegerField(default=0)),
                ('collections_today', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payments_processed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('petty_cash_closing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('workshop_delivery_count', models.PositiveIntegerField(default=0)),
                ('qc_passed_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
