# Generated by Django 5.0.1 on 2026-01-30 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('job_cards', '0008_jobcard_plate_code_jobcard_plate_emirate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_services',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_cards.jobcard')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'created_at'], name='customers_c_custome_a8e44f_idx'), models.Index(fields=['rating'], name='customers_c_rating_360940_idx')],
                'unique_together': {('customer', 'job_card')},
            },
        ),
        migrations.CreateModel(
            name='CustomerPortalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('JOB_VIEW', 'Job View'), ('ESTIMATE_APPROVED', 'Estimate Approved'), ('PAYMENT_MADE', 'Payment Made'), ('FEEDBACK_SUBMITTED', 'Feedback Submitted'), ('BOOKING_CREATED', 'Booking Created')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_cards.jobcard')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer', 'timestamp'], name='customers_c_custome_97d488_idx'), models.Index(fields=['activity_type'], name='customers_c_activit_08ea17_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'is_active'], name='customers_p_token_5d4c1a_idx'), models.Index(fields=['expires_at'], name='customers_p_expires_b071af_idx')],
            },
        ),
    ]
