# Generated by Django 5.2.11 on 2026-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_loyalty_points_customer_preferred_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
