import React, { useState, useEffect, useCallback } from 'react';
import api from '../../api/axios';
import { useNavigate } from 'react-router-dom';
import { PlusCircle, CreditCard, Tag, Upload } from 'lucide-react';
import {
    PortfolioPage,
    PortfolioTitle,
    PortfolioButton,
    PortfolioCard,
    PortfolioInput,
    PortfolioSelect,
    PortfolioTextarea,
    PortfolioSectionTitle
} from '../../components/PortfolioComponents';

const ReceiptVoucher = () => {
    const navigate = useNavigate();
    const [accounts, setAccounts] = useState([]);
    const [loading, setLoading] = useState(true);
    const [formData, setFormData] = useState({
        voucher_no: '', // Will be auto-generated by backend if empty, but UI shows placeholder
        date: new Date().toISOString().split('T')[0],
        receipt_type: 'CASH',
        amount: '',
        payee_name: '', // Receipt To
        account: '', // Credit Account (Income/Customer)
        cheque_number: '',
        cheque_date: '',
        description: '',
        branch: ''
    });

    const [branches, setBranches] = useState([]);

    const fetchMasters = useCallback(async () => {
        try {
            const [accRes, branchRes] = await Promise.all([
                api.get('/finance/api/accounts/'),
                api.get('/api/hr/branches/')
            ]);
            setAccounts(accRes.data);
            setBranches(branchRes.data);
        } catch (err) {
            console.error('Error fetching masters', err);
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => {
        fetchMasters();
    }, [fetchMasters]);

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            // Construct the payload for Voucher + Details
            // Receipt = Debit Cash/Bank, Credit Income/Customer

            // 1. Identification of Debit Account based on Receipt Type
            // For now, we'll look for a 'Cash' or 'Bank' account in the loaded accounts
            // Ideally this should be configured in settings. 
            // We will attempt to find an asset account.
            let debitAccount = null;
            if (formData.receipt_type === 'CASH') {
                debitAccount = accounts.find(a => a.name.toLowerCase().includes('cash') || a.code === '1001'); // Default Cash
            } else {
                debitAccount = accounts.find(a => a.name.toLowerCase().includes('bank') || a.code === '1002'); // Default Bank
            }

            if (!debitAccount) {
                // Fallback if specific accounts not found, maybe show error or use the first Asset account
                debitAccount = accounts.find(a => a.category === 'ASSET');
                if (!debitAccount) {
                    alert("System Configuration Error: No Cash/Bank Asset Accounts found.");
                    return;
                }
            }

            const payload = {
                voucher_number: `RV-${Date.now()}`, // Temporary client-side ID, backend will sanitize
                voucher_type: 'RECEIPT',
                date: formData.date,
                reference_number: formData.cheque_number,
                narration: formData.description,
                payment_mode: formData.receipt_type,
                cheque_number: formData.cheque_number,
                cheque_date: formData.cheque_date || null,
                payee_name: formData.payee_name,
                branch: formData.branch || null,
                status: 'POSTED', // Direct post for now
                details: [
                    {
                        // DEBIT (Cash/Bank)
                        account: debitAccount.id,
                        debit: formData.amount,
                        credit: 0,
                        description: `Receipt from ${formData.payee_name}`
                    },
                    {
                        // CREDIT (Income/Customer)
                        account: formData.account,
                        debit: 0,
                        credit: formData.amount,
                        description: `Revenue/Payment - ${formData.description}`
                    }
                ]
            };

            await api.post('/finance/api/vouchers/', payload);
            navigate('/finance'); // Return to dashboard
        } catch (err) {
            console.error(err);
            alert('Voucher Creation Failed. Please check the form.');
        }
    };

    if (loading) return <div style={{ padding: '80px', textAlign: 'center', color: 'var(--cream)', opacity: 0.5 }}>Loading Financial Masters...</div>;

    return (
        <PortfolioPage breadcrumb="Finance / Vouchers / Receipt">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <PortfolioTitle subtitle="Record incoming payments and revenue recognition.">
                    Receipt Voucher
                </PortfolioTitle>
                <button onClick={() => navigate('/finance')} style={{ background: 'none', border: 'none', color: 'var(--gold)', cursor: 'pointer' }}>
                    <Tag size={20} /> Close
                </button>
            </div>

            <form onSubmit={handleSubmit} style={{ maxWidth: '1200px', marginTop: '40px' }}>
                <PortfolioCard>
                    <div style={{ background: 'var(--primary)', padding: '15px', marginBottom: '20px', borderRadius: '8px', color: 'white', fontWeight: 'bold' }}>
                        ≡ Receipt Voucher
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '30px' }}>
                        {/* Left Column */}
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                            <PortfolioInput
                                label="Voucher No"
                                name="voucher_no"
                                value={formData.voucher_no}
                                disabled
                                placeholder="(Auto-Generated)"
                            />
                            <PortfolioSelect
                                label="Receipt Type"
                                name="receipt_type"
                                value={formData.receipt_type}
                                onChange={handleChange}
                            >
                                <option value="CASH">Cash</option>
                                <option value="CHEQUE">Cheque</option>
                                <option value="CARD">Card</option>
                                <option value="TRANSFER">Bank Transfer</option>
                            </PortfolioSelect>

                            {formData.receipt_type === 'CHEQUE' && (
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                                    <PortfolioInput
                                        label="Cheque No"
                                        name="cheque_number"
                                        value={formData.cheque_number}
                                        onChange={handleChange}
                                    />
                                    <PortfolioInput
                                        label="Cheque Date"
                                        name="cheque_date"
                                        type="date"
                                        value={formData.cheque_date}
                                        onChange={handleChange}
                                    />
                                </div>
                            )}

                            <PortfolioSelect
                                label="Branch Name"
                                name="branch"
                                value={formData.branch}
                                onChange={handleChange}
                            >
                                <option value="">--Select--</option>
                                {branches.map(b => (
                                    <option key={b.id} value={b.id}>{b.name}</option>
                                ))}
                            </PortfolioSelect>

                            <PortfolioInput
                                label="Receipt To (Payee)"
                                name="payee_name"
                                value={formData.payee_name}
                                onChange={handleChange}
                            />

                            <PortfolioInput
                                label="Total Amount"
                                name="amount"
                                type="number"
                                step="0.01"
                                value={formData.amount}
                                onChange={handleChange}
                                required
                            />
                        </div>

                        {/* Right Column */}
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                            <PortfolioInput
                                label="Receipt Date"
                                name="date"
                                type="date"
                                value={formData.date}
                                onChange={handleChange}
                            />

                            <PortfolioSelect
                                label="Account Name (Revenue/Customer)"
                                name="account"
                                value={formData.account}
                                onChange={handleChange}
                                required
                            >
                                <option value="">--Select--</option>
                                {accounts.map(acc => (
                                    <option key={acc.id} value={acc.id}>{acc.name} ({acc.code})</option>
                                ))}
                            </PortfolioSelect>

                            <PortfolioInput
                                label="Job Card No (Optional)"
                                name="reference"
                                value={formData.reference} // abusing 'reference' for Job Card No temporarily or we add job_card link
                                onChange={(e) => setFormData({ ...formData, reference: e.target.value })}
                                placeholder="Job Card Ref..."
                            />

                            <PortfolioTextarea
                                label="Remarks"
                                name="description"
                                value={formData.description}
                                onChange={handleChange}
                                rows={4}
                            />
                        </div>
                    </div>

                    <div style={{ marginTop: '40px', display: 'flex', gap: '15px', justifyContent: 'center' }}>
                        <PortfolioButton variant="gold" type="submit" style={{ width: '150px' }}>Save</PortfolioButton>
                        <PortfolioButton variant="secondary" type="button" onClick={() => setFormData({ ...formData, amount: '', description: '' })} style={{ width: '150px' }}>Reset</PortfolioButton>
                    </div>
                </PortfolioCard>
            </form>
        </PortfolioPage>
    );
};

export default ReceiptVoucher;
