# Generated by Django 6.0.1 on 2026-01-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeramicWarrantyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50, verbose_name='VIN')),
                ('installation_date', models.DateField()),
                ('branch_location', models.CharField(choices=[('DXB', 'Dubai'), ('AUH', 'Abu Dhabi'), ('SHJ', 'Sharjah')], max_length=10)),
                ('coating_brand', models.CharField(max_length=100)),
                ('coating_type', models.CharField(choices=[('CERAMIC', 'Ceramic Coating'), ('GRAPHENE', 'Graphene Coating'), ('QUARTZ', 'Quartz Coating')], max_length=20)),
                ('warranty_period', models.CharField(max_length=50)),
                ('m1_date', models.DateField(blank=True, null=True, verbose_name='1st Maintenance Date')),
                ('m1_notes', models.TextField(blank=True, null=True)),
                ('m2_date', models.DateField(blank=True, null=True, verbose_name='2nd Maintenance Date')),
                ('m2_notes', models.TextField(blank=True, null=True)),
                ('m3_date', models.DateField(blank=True, null=True, verbose_name='3rd Maintenance Date')),
                ('m3_notes', models.TextField(blank=True, null=True)),
                ('m4_date', models.DateField(blank=True, null=True, verbose_name='4th Maintenance Date')),
                ('m4_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
