# Generated by Django 6.0.1 on 2026-01-26 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceramic_warranty', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceramicwarrantyregistration',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceramic_warranty', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='ceramicwarrantyregistration',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
