# Generated by Django 5.0.1 on 2026-01-27 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_cards', '0003_servicecategory_service'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.CharField(choices=[('PPF', 'Paint Protection Film'), ('CERAMIC', 'Ceramic Coating'), ('POLISH', 'Polishing Materials'), ('CLEANING', 'Cleaning Supplies'), ('TOOLS', 'Workshop Tools'), ('OTHER', 'Other Consumables')], max_length=20)),
                ('unit', models.CharField(default='Units', max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('safety_level', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_restock', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Restock (Purchase)'), ('OUT', 'Consumption (Job)'), ('ADJ', 'Adjustment (Audit)')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem')),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_cards.jobcard')),
            ],
        ),
    ]
