# Generated by Django 5.2.11 on 2026-02-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_purchaseorder_supplier_stockmovement_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
