# Generated by Django 5.2.11 on 2026-02-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_supplier_credit_limit_supplier_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='bin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Main Warehouse', max_length=100),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='rack',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
